### ISSUE TITLE
Proof read website 

### ISSUE THREAD

**Issue by JensWehner** [votca/votca.github.io#2]

**Comment by JoshuaSBrown** [comment]
Ya, I can probably help with this. Missed the meeting this morning due to another engagement.

**Comment by baumeier** [comment]
Proof reading only, or collecting a list of things to add, too?

**Comment by JensWehner** [comment]
Feel free to add things as well, if they are bigger, I would prefer to create a separate issue/pr.

**Comment by junghans** [comment]
This is always ongoing!
